version: '3'

services:
  web:
    build: .
    command: ["./wait-for-db.sh", "db:5432", "python", "manage.py", "migrate", "&&", "gunicorn", "credit_approval_system.wsgi:application", "--bind", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'creditapp_db'
      POSTGRES_USER: 'virat'
      POSTGRES_PASSWORD: 'prajwal'
    ports:
      - "5432:5432"
